apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: active-passive-appset
  namespace: active-passive-gitops 
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          color: 'blue'
      values:
        clusterName: '{{.name}}'
        clusterURL: '{{.url}}'
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{.values.clusterName}}-active-passive'
    spec:
      destination:
        namespace: bg-rollout
        server: '{{.values.clusterURL}}'
      project: default
      source:
        path: bg-rollout
        repoURL: 'https://github.com/jiribaloun/ocp-deployment.git'
        targetRevision: main
