apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: active-passive-appset
  namespace: active-passive-gitops 
spec:
generators:
- clusters:
    selector:
      matchLabels:
        color: "blue"
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{.cluster}}-active-passive'
    spec:
      destination:
        namespace: bg-rollout
        server: '{{ .url}}'
      project: default
      source:
        path: bg-rollout
        repoURL: 'https://github.com/jiribaloun/ocp-deployment.git'
        targetRevision: main
