apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: active-passive-appset
  namespace: active-passive-gitops 
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
          - key: LocaTion
            operator: In
            values:
              - "TOR"
      values:
        clusterName: '{{.name}}'
        clusterURL: '{{.server}}'
        OCPlocation: '{{.metadata.labels.LocaTion}}' 
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{.values.clusterName}}-{{.values.OCPlocation | lower }}-active-passive'
    spec:
      destination:
        namespace: bg-rollout
        server: '{{.values.clusterURL}}'
      project: default
      source:
        path: bg-rollout
        repoURL: 'https://github.com/jiribaloun/ocp-deployment.git'
        targetRevision: main
      syncPolicy:
        automated:
          prune: true
