apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: active-passive-appset
  namespace: active-passive-gitops 
spec:
  generators:
  - clusters:
      selector:
        matchExpressions:
          - key: location
            operator: In
            values:
              - "tor"
              - "bar"
      values:
        clusterName: '{{.name}}'
        clusterURL: '{{.server}}'
        OCPlocation: '{{.metadata.labels.location}}' 
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  template:
    metadata:
      name: '{{.values.clusterName}}-{{.values.OCPlocation}}-active-passive'
    spec:
      destination:
        namespace: bg-rollout
        server: '{{.values.clusterURL}}'
      project: default
      source:
        path: bg-rollout
        repoURL: 'https://github.com/jiribaloun/ocp-deployment.git'
        targetRevision: main
