apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-bluegreen
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
      - image: argoproj/rollouts-demo:red
        imagePullPolicy: Always
        name: rollouts-demo
        ports:
        - containerPort: 8080
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      volumeMounts:
        - mountPath: '/mnt'
          name: nfs-bg-rollout-mnt
      volumes:
      - name: nfs-bg-rollout-mnt
        persistentVolumeClaim:
          claimName: nfs-bg-rollout-pvc            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
